elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
nagios:
    image: mkodockx/docker-nagios
    volumes:
        - /opt/dockx/nagios/config:/opt/nagios/etc
        - /opt/dockx/nagios/var:/opt/nagios/var
        - /opt/dockx/nagios/log:/var/log/apache2
    environment:
        - NAGIOSADMIN_USER=nagios
        - NAGIOSAMDIN_PASS=nagios
